### ISSUE TITLE
Program runs!!! Incorrect estimates.

### ISSUE THREAD

**Issue by jacobcvt12** [Jacobcvt12/bm1_project#10]
Hey guys, exciting news. The program runs! Unfortunately, the estimated parameters aren't quite right... Would you guys mind looking through my code to be sure that the logic makes sense? It may just be that I need to fiddle around with the deltas more.

@KhatriVivek @Tharper84

**Comment by KhatriVivek** [comment]
Cool. In the process of working my way through the code. Can you explain the part below?

for (int s = 1; s < S + B; ++s) {
        if (s % 100 == 0) {
            Rcpp::Rcout << s << std::endl;
                                               }

**Comment by jacobcvt12** [comment]
Rcout is used to print (from Rcpp). The percent is the modulus operator. So for every one hundred iterations, print out the iteration number.

**Comment by KhatriVivek** [comment]
Is the code below just creating a vector x_s_star that has the same length as x_s

Rcpp::NumericVector x_s_star(x_s.length());

**Comment by KhatriVivek** [comment]
When x_s(i) is a 0, the modulo below will 0.5. By using int, are your forcing 0.5 to be a zero?

 int (x_s(i) + 1) % 2

**Comment by jacobcvt12** [comment]
Yes to the first post.

**Comment by jacobcvt12** [comment]
I'm forcing x_s(i) + 1 to be an integer.

**Comment by KhatriVivek** [comment]
Still not completely sure what you are doing with the code below...If x_s(i)= 0 then will x_star(i) equal 0.5 ? If x_s(i) = 1 then will x_star(i)=0? 

for (int i = 0; i < x_s.length(); i++) {
            x_s_star(i) = int (x_s(i) + 1) % 2;
        }

**Comment by KhatriVivek** [comment]
In the code below, you have likelihood minus likelihood but why isn't it likelihood*p(Xi=h) where the probability that Xi=h comes from the last iteration by summing the number of h's and dividing by the number of subjects?

log_r = R::dnorm(y(i), theta2, 1/sqrt(s2), true) -
                    R::dnorm(y(i), theta1, 1/sqrt(s1), true);

**Comment by jacobcvt12** [comment]
If x_s(i) = 0, then x_s_star(i) should equal 1. The point of the adding 1 and then taking the modulus of 2 is to switch between 0 and 1 (could have been an if statement as well).

To your second point, you're right that I'm not adding the likelihood of x and x\* given the prior probability (which is 0.5). The reason that I am not is because 0 and 1 are equally likely with a prior probability of 0.5. 

i.e.
dbinom(1, 1, 0.5) = dbinom(0, 1, 0.5)

They both occur with probability 0.5.

**Comment by jacobcvt12** [comment]
What I've noticed is that theta1 and theta2 both converge to the mean of the data, and similar for s1 and s2. p always converges to 0.5. I'm not sure, but I wonder if there's something that I did incorrectly with MH for p.

**Comment by jacobcvt12** [comment]
I think that the problem is with a combination of the x's and p's. I'm going to send an email to Rob and I'll cc you two.

**Comment by jacobcvt12** [comment]
I've gotten the estimates to work out. It was a matter of proposing the opposite value for each x with some probability, like Rob said. I've also gotten the adaptive delta to work. The estimates are pretty decent - the HPD covers the true value in most of the simulations I ran. 

I think we can move onto RJ at this point.

**Comment by jacobcvt12** [comment]
By the way, this updated code is in the branch **multisource**

**Comment by KhatriVivek** [comment]
Looked at the revised code. I see that you changed the data generation
process as Rob suggested. For 2 classes I guess you could also just do
rbinom(number of subjects,1,0.3)

And that are using the acceptance ratio as parameter to a Bernoulli which
determines whether the latent class is switched.

**Comment by KhatriVivek** [comment]
If I'm understanding correctly, if your acceptance rate for the last 100 iterations is less than 0.3 then you produced a bernoulli variable with probability 0.3 to determine if a switch is made for the latent class. It is interesting that 0.3 also happends to be the weight on component 1. Do you think the choice of 0.3 influenced things at all?
