### ISSUE TITLE
running Jacob's code

### ISSUE THREAD

**Issue by KhatriVivek** [Jacobcvt12/bm1_project#12]
I'm almost there....by using the line below, I am able to get the circular buffer from the boost library

// [[Rcpp::depends(BH)]]

but now I am getting the error

'to_string' is not a member of 'std' when I attempt to run the line below

 delta.track_parameter("x" + std::to_string (i), 0.3);

Any thoughts? Thanks!

**Comment by jacobcvt12** [comment]
You need to use the c++11 standard. You can set this in a Makevars file - not sure where this is stored on windows though.
