### ISSUE TITLE
Simulated data

### ISSUE THREAD

**Issue by jacobcvt12** [Jacobcvt12/bm1_project#3]
Hey @KhatriVivek and @Tharper84 . I went ahead and added some **really** basic simulated data (using the script R/data.R). Feel free to update this. 

I was thinking we would start with just two components (so that we can use the beta distribution) and once that works, we'll extend to multiple components (where we have to use the dirichlet distribution as a prior).

What do you guys think?

**Comment by Tharper84** [comment]
How bout before class tuesday you explain what your doing there. I think that your "really basic" is "stupendously complex" for me.

**Comment by jacobcvt12** [comment]
Sure we can chat on Tuesday.
