### ISSUE TITLE
Proposal distribution for latent classes

### ISSUE THREAD

**Issue by jacobcvt12** [Jacobcvt12/bm1_project#4]
How do we draw new values of x_i\* from a proposal distribution? It seems pretty straightforward for the other parameters, i.e. p\* simulated from N(p(s), delta^2), or unif(p(s)-delta, p(s)+delta). 

Any thoughts?

@KhatriVivek @Tharper84

**Comment by KhatriVivek** [comment]
As for a proposal of x_i*, like in the homework, couldn't we just do
rbinom(number of subjects,1, p) with the the p sampled from its prior?

**Comment by jacobcvt12** [comment]
That's what I've done with the code for right now. Just don't know how you're supposed to tune that. I'm just not quite sure if that makes sense. I think you end up accepting all or almost all proposals. Maybe we can send an email to Rob to check. I haven't been able to find anything online.

**Comment by KhatriVivek** [comment]
That's just for the initial proposal. Below is what I did for the
homework...including the tuning.

[image: Inline image 2]

**Comment by jacobcvt12** [comment]
Oh I guess I didn't specify - I was assuming that the Metropolis-Hastings algorithm would be simpler here than Gibbs. I have no idea how the full conditionals will work out when including **k** (number of components) as a parameter to be estimated.

**Comment by KhatriVivek** [comment]
I need to read up more on the Metropolos-Hastings algorithm and reverse
jump MCMC. That is my plan for tomorrow morning.

**Comment by jacobcvt12** [comment]
Sounds good. I'm currently programming what's basically a MH version of our homework for a two component univariate case. Once that's done, I think we should adjust for a multiple component case. Then the challenge will be reversible jump MCMC (which I still need to read over as well). If we can get that running, and still have time, it would be cool to implement a reversible-jump MCMC, if you guys are interested.
