### ISSUE TITLE
RJ MCMC algorithm

### ISSUE THREAD

**Issue by jacobcvt12** [Jacobcvt12/bm1_project#8]
Find an RJ MCMC algorithm.

**Comment by Tharper84** [comment]
I found a couple of pdfs showing that they just use the sample covariance matrix for a multivariate normal proposal distribution in Metropolis-Hastings, which probably means that's its ok to use the sample variance as the variance in a univariate proposal distribution

**Comment by jacobcvt12** [comment]
Have either of you had any luck with finding an algorithm?

**Comment by KhatriVivek** [comment]
Have not been able to find anything that it is accessible to me. Maybe you
could ask for Rob for a hint after he replies to the email you just sent.

**Comment by KhatriVivek** [comment]
Until it got into measure theory, was finding the article below to be easy
to follow.

https://www.seas.harvard.edu/courses/cs281/papers/hastie-green-2011.pdf

Currently going through the references to see if they are easier to follow.

**Comment by KhatriVivek** [comment]
skipped ahead in the paper I mentioned before to Section 3.1. Still working through it but it might help us.
