### ISSUE TITLE
boost library

### ISSUE THREAD

**Issue by KhatriVivek** [Jacobcvt12/bm1_project#9]
Still trying to figure out how to include the boost C++ library.

I found this link 

http://www.boost.org/users/history/version_1_57_0.html

After I download and decompress

boost_1_57_0.zip

I end  up with a folder called  "boost_1_57". Within which is another folder called "boost". Within boost is the folder circular buffer. But within boost folder, there is no file "circular_buffer.hp". Should I be seeing such a file? Do I need to put that file within the folder Rcpp/include ?

**Comment by KhatriVivek** [comment]
should have written "circular_buffer.hpp"

**Comment by jacobcvt12** [comment]
So I looked into it, and it's a little trickier to install boost on Windows (on Mac and Linux, you can use a package manager from the command line to install programs). You're required to install either Visual Studio or cygwin to install Boost. I removed the bit requiring the circular buffer for right now. Let's go back to that once we get the reversible jump working. 

http://www.boost.org/doc/libs/1_55_0/more/getting_started/windows.html

**Comment by KhatriVivek** [comment]
Been looking for accessible material for reversible jumo MCMC for the last couple hours. No luck as of yet. Will keep looking.

**Comment by jacobcvt12** [comment]
Thanks!
